---
title: "Turk20 Analysis"
author: "Eric Hare"
date: "November 2, 2015"
output: html_document
---

```{r}
results <- read.csv("turk20_results.csv")
users <- read.csv("turk20_users.csv")
details <- read.csv("picture-details.csv")
```

```{r}
library(ggplot2)
library(dplyr)

merged <- merge(results, details[,c("pic_id", "obs_plot_location")])
merged$response_no <- factor(merged$response_no)

merged_filter <- merged %>% filter(!(nick_name %in% c("AG7F3QKOQJGYR", "558ab68afdf99b6567d0081d")))

lapply(unique(merged$pic_id), function(id) {
    subbed <- merged[merged$pic_id == id,]
    subbed$dataplot <- subbed$response_no == subbed$obs_plot_location
    
    qplot(response_no, geom = "bar", data = subbed, fill = dataplot) +   
        scale_x_discrete(drop = FALSE) +
        ylim(c(0, 20)) +
        theme_bw() +
        ggtitle(paste("Distribution of Responses for Plot", id))
})

pvalues <- sapply(unique(merged$pic_id), function(id) {
    subbed <- merged[merged$pic_id == id,]
    subbed$dataplot <- subbed$response_no == subbed$obs_plot_location
    
    m <- 12
    K <- nrow(subbed)
    x <- sum(subbed$dataplot)
    
    sum(choose(K, x:K) * (1 / m)^(x:K) * ((m - 1) / m)^(K - x:K))
})

sapply(unique(merged_filter$pic_id), function(id) {
    subbed <- merged_filter[merged_filter$pic_id == id,]
    subbed$dataplot <- subbed$response_no == subbed$obs_plot_location
    
    sum(subbed$dataplot)
})

pvalues < .05
```

